### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by circled-square** [unitn-baccala/Back-end#1]
API:

- [x] registrazione: POST /api/user
- [x] deregistrazione: DELETE /api/user
- [x] login: POST /api/authenticate
- [x] crea ingr.: POST /api/ingredient
- [x] elimina ingr.: DELETE  /api/ingredient
- [x] lista ingr.: GET /api/ingredient
- [x] crea piatto: POST /api/dish
    - [x] accetta immagini in base64 per POST /api/dish
- [x] elimina piatto: DELETE /api/dish
- [x] lista piatti: GET /api/dish
- [x] crea menù: POST /api/menu
- [x] elimina menù: DELETE /api/menu
- [x] lista menù: GET /api/menu
- [x] crea categoria: POST /api/category
- [x] elimina categoria: DELETE /api/category
- [x] lista categoria: GET /api/category
- [x] pagina menù per utente finale: GET /api/menu/full

- [x] docs

- [ ] #2

**Comment by Kalsifer-7** [comment]
api menu da provare ma sono state implementate
